import { OntologyEdge, OntologyNode } from "./types";

// 실제 데이터 연동 전까지 화면 확인용으로 만든 목업 데이터.
// 스펙 3장 스키마(Asset/Industry/Sector/Concept, BELONGS_TO/COMPETES_WITH/AFFECTS)를 그대로 흉내낸다.

export const mockNodes: OntologyNode[] = [
  // 섹터
  { id: "sector-tech", type: "Sector", name: "기술" },
  { id: "sector-energy", type: "Sector", name: "에너지" },

  // 산업
  { id: "industry-semi", type: "Industry", name: "반도체" },
  { id: "industry-software", type: "Industry", name: "소프트웨어" },
  { id: "industry-oilgas", type: "Industry", name: "석유·가스" },

  // 종목
  {
    id: "asset-nvda",
    type: "Asset",
    name: "엔비디아",
    ticker: "NVDA",
    price: 187.62,
    changePercent: 2.4,
    companySummary:
      "GPU(그래픽 처리 장치)를 설계하는 반도체 기업. 최근에는 AI 모델 학습·추론용 칩 수요로 주목받고 있다.",
    ceo: "젠슨 황",
    marketCap: "4.6T",
    news: [
      {
        title: "엔비디아, 차세대 AI 칩 로드맵 공개",
        summary: "데이터센터용 신규 GPU 아키텍처 발표, 내년 양산 예정.",
        url: "https://example.com/news/nvda-1",
        publishedAt: "2026-08-01",
        source: "예시뉴스",
        sentiment: "positive",
      },
      {
        title: "반도체 수출 규제 이슈 재점화",
        summary: "일부 국가향 첨단 칩 수출 제한 가능성이 다시 거론됨.",
        url: "https://example.com/news/nvda-2",
        publishedAt: "2026-07-28",
        source: "예시뉴스",
        sentiment: "negative",
      },
      {
        title: "1분기 데이터센터 매출 시장 예상치 상회",
        summary: "AI 서버 수요 지속으로 실적이 시장 예상을 웃돌았다.",
        url: "https://example.com/news/nvda-3",
        publishedAt: "2026-07-20",
        source: "예시뉴스",
        sentiment: "positive",
      },
    ],
    outlook: {
      summary:
        "AI 데이터센터 투자 확대가 이어지는 가운데, 수출 규제와 금리 변화가 주요 변수로 꼽힌다. (예시 텍스트)",
      riskFactors: ["수출 규제 강화 가능성", "금리 상승에 따른 밸류에이션 부담"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },
  {
    id: "asset-amd",
    type: "Asset",
    name: "AMD",
    ticker: "AMD",
    price: 162.15,
    changePercent: -1.1,
    companySummary: "CPU·GPU를 설계하는 반도체 기업. 엔비디아의 주요 경쟁사.",
    ceo: "리사 수",
    marketCap: "260B",
    news: [
      {
        title: "AMD, AI 가속기 신제품 발표",
        summary: "엔비디아 대비 가격 경쟁력을 강조한 신규 가속기 공개.",
        url: "https://example.com/news/amd-1",
        publishedAt: "2026-07-30",
        source: "예시뉴스",
        sentiment: "positive",
      },
    ],
    outlook: {
      summary: "AI 가속기 시장 점유율 확대를 노리고 있으나 경쟁 심화가 부담. (예시 텍스트)",
      riskFactors: ["엔비디아와의 경쟁 심화"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },
  {
    id: "asset-msft",
    type: "Asset",
    name: "마이크로소프트",
    ticker: "MSFT",
    price: 421.3,
    changePercent: 0.6,
    companySummary: "Windows, Office, Azure 클라우드를 운영하는 소프트웨어 기업.",
    ceo: "사티아 나델라",
    marketCap: "3.1T",
    news: [
      {
        title: "Azure AI 서비스 매출 성장세 지속",
        summary: "클라우드 AI 서비스 부문이 전체 성장을 견인.",
        url: "https://example.com/news/msft-1",
        publishedAt: "2026-07-29",
        source: "예시뉴스",
        sentiment: "positive",
      },
    ],
    outlook: {
      summary: "클라우드·AI 서비스 확장이 실적을 뒷받침하는 흐름. (예시 텍스트)",
      riskFactors: ["대규모 데이터센터 투자에 따른 비용 부담"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },
  {
    id: "asset-crm",
    type: "Asset",
    name: "세일즈포스",
    ticker: "CRM",
    price: 258.4,
    changePercent: -0.3,
    companySummary: "고객관계관리(CRM) 소프트웨어를 제공하는 기업.",
    ceo: "마크 베니오프",
    marketCap: "245B",
    news: [
      {
        title: "세일즈포스, AI 에이전트 기능 확대",
        summary: "영업 자동화용 AI 에이전트 신기능을 발표.",
        url: "https://example.com/news/crm-1",
        publishedAt: "2026-07-25",
        source: "예시뉴스",
        sentiment: "neutral",
      },
    ],
    outlook: {
      summary: "AI 기능 확장이 신규 계약에 미치는 영향을 지켜볼 필요가 있다. (예시 텍스트)",
      riskFactors: ["기업 IT 지출 둔화 가능성"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },
  {
    id: "asset-xom",
    type: "Asset",
    name: "엑슨모빌",
    ticker: "XOM",
    price: 118.7,
    changePercent: 1.2,
    companySummary: "원유·천연가스 탐사 및 정제를 하는 에너지 기업.",
    ceo: "대런 우즈",
    marketCap: "480B",
    news: [
      {
        title: "엑슨모빌, 원유 증산 계획 발표",
        summary: "주요 유전 지역에서 생산량 확대 계획을 공개.",
        url: "https://example.com/news/xom-1",
        publishedAt: "2026-07-27",
        source: "예시뉴스",
        sentiment: "neutral",
      },
    ],
    outlook: {
      summary: "유가 흐름과 증산 계획이 실적의 핵심 변수. (예시 텍스트)",
      riskFactors: ["국제 유가 변동성"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },
  {
    id: "asset-cvx",
    type: "Asset",
    name: "셰브론",
    ticker: "CVX",
    price: 152.9,
    changePercent: 0.8,
    companySummary: "원유·천연가스 탐사 및 정제를 하는 에너지 기업. 엑슨모빌의 주요 경쟁사.",
    ceo: "마이크 워스",
    marketCap: "290B",
    news: [
      {
        title: "셰브론, 배당 확대 발표",
        summary: "주주환원 정책 강화 차원에서 배당 인상을 발표.",
        url: "https://example.com/news/cvx-1",
        publishedAt: "2026-07-22",
        source: "예시뉴스",
        sentiment: "positive",
      },
    ],
    outlook: {
      summary: "안정적인 현금흐름을 바탕으로 주주환원을 강화하는 흐름. (예시 텍스트)",
      riskFactors: ["국제 유가 변동성"],
      generatedAt: "2026-08-03T09:00:00+09:00",
    },
  },

  // 개념
  {
    id: "concept-rates",
    type: "Concept",
    name: "금리",
    category: "거시",
    description: "중앙은행 기준금리 및 시중 금리 수준.",
  },
  {
    id: "concept-inflation",
    type: "Concept",
    name: "인플레이션",
    category: "거시",
    description: "물가 상승률 추이.",
  },
  {
    id: "concept-quantum",
    type: "Concept",
    name: "양자컴퓨팅",
    category: "기술",
    description: "양자컴퓨터 기술 발전 및 상용화 속도.",
  },
  {
    id: "concept-ai-demand",
    type: "Concept",
    name: "AI 수요",
    category: "기술",
    description: "AI 모델 학습·서비스에 대한 산업 전반의 수요.",
  },
];

export const mockEdges: OntologyEdge[] = [
  // BELONGS_TO: Industry -> Sector
  { id: "e-belongs-semi-tech", source: "industry-semi", target: "sector-tech", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-sw-tech", source: "industry-software", target: "sector-tech", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-oilgas-energy", source: "industry-oilgas", target: "sector-energy", type: "BELONGS_TO", direction: "단방향" },

  // BELONGS_TO: Asset -> Industry
  { id: "e-belongs-nvda-semi", source: "asset-nvda", target: "industry-semi", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-amd-semi", source: "asset-amd", target: "industry-semi", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-msft-sw", source: "asset-msft", target: "industry-software", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-crm-sw", source: "asset-crm", target: "industry-software", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-xom-oilgas", source: "asset-xom", target: "industry-oilgas", type: "BELONGS_TO", direction: "단방향" },
  { id: "e-belongs-cvx-oilgas", source: "asset-cvx", target: "industry-oilgas", type: "BELONGS_TO", direction: "단방향" },

  // COMPETES_WITH
  { id: "e-competes-nvda-amd", source: "asset-nvda", target: "asset-amd", type: "COMPETES_WITH", direction: "양방향" },
  { id: "e-competes-msft-crm", source: "asset-msft", target: "asset-crm", type: "COMPETES_WITH", direction: "양방향" },
  { id: "e-competes-xom-cvx", source: "asset-xom", target: "asset-cvx", type: "COMPETES_WITH", direction: "양방향" },

  // AFFECTS: Concept -> Concept / Asset
  {
    id: "e-affects-rates-inflation",
    source: "concept-rates",
    target: "concept-inflation",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "negative",
    strength: 4,
    confidence: 0.7,
    rationale: "금리 인상은 소비·투자를 위축시켜 인플레이션을 억제하는 방향으로 작용한다.",
  },
  {
    id: "e-affects-rates-nvda",
    source: "concept-rates",
    target: "asset-nvda",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "negative",
    strength: 3,
    confidence: 0.55,
    rationale: "성장주는 금리 상승 시 미래 이익의 현재가치가 낮아져 주가에 부담이 된다.",
  },
  {
    id: "e-affects-rates-msft",
    source: "concept-rates",
    target: "asset-msft",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "negative",
    strength: 2,
    confidence: 0.5,
    rationale: "대형 기술주 역시 금리 상승기에 밸류에이션 압박을 받는 경향이 있다.",
  },
  {
    id: "e-affects-inflation-xom",
    source: "concept-inflation",
    target: "asset-xom",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 3,
    confidence: 0.6,
    rationale: "에너지 가격 상승은 인플레이션과 함께 움직이는 경향이 있어 에너지 기업 매출에 우호적일 수 있다.",
  },
  {
    id: "e-affects-inflation-cvx",
    source: "concept-inflation",
    target: "asset-cvx",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 3,
    confidence: 0.6,
    rationale: "에너지 가격 상승은 인플레이션과 함께 움직이는 경향이 있어 에너지 기업 매출에 우호적일 수 있다.",
  },
  {
    id: "e-affects-quantum-nvda",
    source: "concept-quantum",
    target: "asset-nvda",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 4,
    confidence: 0.4,
    rationale: "양자컴퓨팅 연구 확대가 관련 반도체·컴퓨팅 인프라 수요로 이어질 수 있다는 관측 (근거는 아직 약함).",
  },
  {
    id: "e-affects-ai-nvda",
    source: "concept-ai-demand",
    target: "asset-nvda",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 5,
    confidence: 0.8,
    rationale: "AI 데이터센터 투자 확대가 GPU 수요로 직접 연결되어 매출을 견인하고 있다.",
  },
  {
    id: "e-affects-ai-amd",
    source: "concept-ai-demand",
    target: "asset-amd",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 4,
    confidence: 0.65,
    rationale: "AI 가속기 수요 확대의 수혜를 함께 받고 있다.",
  },
  {
    id: "e-affects-ai-msft",
    source: "concept-ai-demand",
    target: "asset-msft",
    type: "AFFECTS",
    direction: "단방향",
    polarity: "positive",
    strength: 3,
    confidence: 0.6,
    rationale: "Azure의 AI 서비스 수요 증가가 클라우드 매출 성장에 기여하고 있다.",
  },
];

export const nodeById = new Map(mockNodes.map((n) => [n.id, n]));
